### ISSUE TITLE
Set up OpenShift-CI integration for auto-merges

### ISSUE THREAD

**Issue by anishasthana** [project-codeflare/codeflare-operator#1]
https://github.com/openshift/release

We can use the tide plugin to control merges to main. This will require us generating a new OWNERS file in the repository as well -- right now I imagine the approvers (and reviewers) will be me and @Maxusmusti

**Comment by accorvin** [comment]
@anishasthana we should have a discussion about whether we use openshift-ci for this or GitHub actions (I believe we're using GitHub actions elsewhere in the project-codeflare org today, @Maxusmusti can confirm).

**Comment by anishasthana** [comment]
Definitely worth a discussion! I wasn't aware about project-codeflare's existing ci.

**Comment by anishasthana** [comment]
Automerges are working
