### ISSUE TITLE
Automate the CodeFlare release process.

### ISSUE THREAD

**Issue by amsharma3** [project-codeflare/codeflare-operator#107]
Automated end to end CodeFlare release process.

Some helpful documents -
1. Codeflare branching strategy: https://github.com/project-codeflare/adr/blob/main/PCF-ADR-0002-release-story-and-branch-maintenance.md  
2. Codeflare release process: https://github.com/project-codeflare/adr/blob/main/PCF-ADR-0003-codeflare-release-process.md

**Comment by sutaakar** [comment]
The task consists of several phases:
- Check current repositories to figure out which repositories are regularly released
- Add release steps into readme for repositories which are released but missing release info
- Adjust https://github.com/project-codeflare/adr/blob/main/PCF-ADR-0003-codeflare-release-process.md#release-process  to contain list of repositories included in release with links
- Analyze every release process and remove manual steps if needed, ideally make a repository release fully automatic (i.e. GitHub actions script for release)

**Comment by sutaakar** [comment]
Created new tasks to review and adjust readme with release instructions:
https://github.com/project-codeflare/codeflare-cli/issues/994
https://github.com/project-codeflare/codeflare-operator/issues/108
https://github.com/project-codeflare/codeflare-sdk/issues/127
https://github.com/project-codeflare/instascale/issues/72
https://github.com/project-codeflare/multi-cluster-app-dispatcher/issues/394

**Comment by KPostOffice** [comment]
https://github.com/orgs/project-codeflare/projects/8/views/1?pane=issue&itemId=27882313

The above PR includes a GitHub action that can be manually triggered to create a tag as well as corresponding operator images
