### ISSUE TITLE
Automate updates to InstaScale test result images

### ISSUE THREAD

**Issue by anishasthana** [project-codeflare/codeflare-operator#128]
https://github.com/project-codeflare/codeflare-operator/pull/120 introduced the ability to update the CodeFlare being used for a test case. The issue however is that when you update the `Default` value for the deployment, the test cases are outdated.

https://github.com/project-codeflare/codeflare-operator/pull/127/commits/8c7803e22ae8c93b1865b7886ad544a54d73de15 is an example commit fixing the test failures.

We should determine a fix for this. One of the options is to update https://github.com/project-codeflare/codeflare-operator/blob/main/Makefile#L104 to also edit the test results.

**Comment by sutaakar** [comment]
Another option is for tests to fetch the proper image directly from https://github.com/project-codeflare/codeflare-operator/blob/main/controllers/defaults.go and replace a placeholder in test resource.

**Comment by astefanutti** [comment]
This has become obsolete with #279.
