### ISSUE TITLE
Ray error when using python version != 3.8.x

### ISSUE THREAD

**Issue by dimakis** [project-codeflare/codeflare-operator#176]
When running the hf_interactive.ipynb,
this error appears:
```
RuntimeError: Python minor versions differ between client and server: client is 3.9.16, server is 3.8.13
```
during the ray.init method:
`---> 14 ray.init(address=f'{ray_cluster_uri}', runtime_env=runtime_env)`

Investigate and fix

**Comment by MichaelClifford** [comment]
@dimakis is this using the codeflare notebook image? When initializing an interactive session between the client and the ray clusters using `ray.init()` the environments need to be similar with the same version of Ray and Python.  

https://discuss.ray.io/t/what-if-python-version-doesnt-match-between-client-and-server/6914

**Comment by dimakis** [comment]
ah thanks @MichaelClifford, so because of the cloudpickle dependancy, we essentially can't do anything? This change needs to happen to either cloud pickle or kuberay right?
should we close out this issue or do we foresee someone from RH contributing a fix/ edit for this to kuberay?

**Comment by MichaelClifford** [comment]
Let's close this issue for now, as it's currently the intended supported behavior of Ray. If it is an issue that should be addressed we should open an issue on the Ray project.
