### ISSUE TITLE
Create upgrade e2e scenario covering upgrade during training

### ISSUE THREAD

**Issue by sutaakar** [project-codeflare/codeflare-operator#184]
Scenario should start a training, perform an operator upgrade during training and finish the training.

Covered features:
- ability of the new operator to process CRs created by old operator
- ability of CodeFlare SDK to connect to existing Cluster and work with AppWrapper created by previous version  (i.e. one client session creates an AppWrapper, a later client session can delete/get the AppWrapper)

**Comment by sutaakar** [comment]
@astefanutti What do you think about this scenario?

**Comment by astefanutti** [comment]
@sutaakar I agree it'd be critical to assess existing operands are not affected by the upgrade, especially those that are not in terminal states.
