### ISSUE TITLE
Install CodeFlare Operator with custom MCAD and Instascale images

### ISSUE THREAD

**Issue by ChristianZaccaria** [project-codeflare/codeflare-operator#186]
Currently when installing the CodeFlare Stack the latest versions of MCAD and Instascale get added to the cluster. 

## Issue
We want documentation on how to make use of custom CodeFlare stack images. Currently, there is no straightforward way of achieving this as i.e., MCAD has its own [tags set to "latest"](https://github.com/project-codeflare/multi-cluster-app-dispatcher/blob/de677ec65ebdfcf82ca0355505b21d8f429d4f79/deployment/mcad-controller/values.yaml#L11) which may need to be substituted to point to our custom image.

## Suggested Resolution
- Create a Make command that takes in two arguments for MCAD and Instascale image locations and substitutes the image locations within the codeflare-operator codebase.
- MCAD and Instascale will need to have the new custom image locations with their tags instead of "latest", perhaps the use of `sed` or `awk` can be used.

**Comment by sutaakar** [comment]
@ChristianZaccaria There is already a support for custom MCAD and InstaScale images in operator resources, see https://github.com/project-codeflare/codeflare-operator/blob/9c269d0881a0a37166c120963d747b543413df4e/config/crd/bases/codeflare.codeflare.dev_mcads.yaml#L42 and https://github.com/project-codeflare/codeflare-operator/blob/9c269d0881a0a37166c120963d747b543413df4e/config/crd/bases/codeflare.codeflare.dev_instascales.yaml#L38

You can specify custom image in MCAD and InstaScale CR.

**Comment by ChristianZaccaria** [comment]
> @ChristianZaccaria There is already a support for custom MCAD and InstaScale images in operator resources, see
> 
> https://github.com/project-codeflare/codeflare-operator/blob/9c269d0881a0a37166c120963d747b543413df4e/config/crd/bases/codeflare.codeflare.dev_mcads.yaml#L42
> 
> and
> https://github.com/project-codeflare/codeflare-operator/blob/9c269d0881a0a37166c120963d747b543413df4e/config/crd/bases/codeflare.codeflare.dev_instascales.yaml#L38
> 
> You can specify custom image in MCAD and InstaScale CR.

Thanks for letting me know Karel, it works perfectly. This is great so I guess I'll just add more documentation on this feature as @anishasthana mentioned.

**Comment by dimakis** [comment]
This will be redundant with new CFO design
