### ISSUE TITLE
RHODS Branding

### ISSUE THREAD

**Issue by KPostOffice** [project-codeflare/codeflare-operator#210]
Change CSV and CRDs to have RHODS branding downstream for 1.32
 
 https://redhat-internal.slack.com/archives/C05F5G4FD7Y/p1691416637995589?thread_ts=1691077767.286749&cid=C05F5G4FD7Y

**Comment by anishasthana** [comment]
Can you open this ticket in the red-hat-data-services fork of the CodeFlare Operator repository?

**Comment by KPostOffice** [comment]
https://github.com/red-hat-data-services/codeflare-operator/issues/29
