### ISSUE TITLE
The InstaScale image versions are inconsistent.

### ISSUE THREAD

**Issue by chandlermoon** [project-codeflare/codeflare-operator#257]
The version tag of InstaScale in Codeflare Operator, v.0.0.7, is inconsistent with the version tag of the InstaScale image in the quay.io repository, v0.0.7, due to an extra dot symbol. This mismatch causes a failure to pull the InstaScale image during the installation of Codeflare Operator.
![1693380150157](https://github.com/project-codeflare/codeflare-operator/assets/35758804/c7765896-6003-499d-83db-72cc6be338e0)
![1693380150157](https://github.com/project-codeflare/codeflare-operator/assets/35758804/11ecfc96-06d9-477d-8619-dd0abf735715)
![1693380192664](https://github.com/project-codeflare/codeflare-operator/assets/35758804/45f0c4d9-41f6-4fe8-a783-69fbd5439bea)

**Comment by sutaakar** [comment]
@chandlermoon Thanks for the report.
There is a new operator release in progress, which will fix this issue.

**Comment by anishasthana** [comment]
Thank you @chandlermoon ! The new release should have resolved this. It will be available once https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3166 is merged
