### ISSUE TITLE
Guide to install on vanilla k8s with the Openshift bits removed

### ISSUE THREAD

**Issue by ashahab** [project-codeflare/codeflare-operator#297]
## WHY
Why is this change being made?
Is there a documentation/guide to deploy this on vanilla k8s with no Openshift dependencies? Is there a helm chart?
## WHAT
What is being asked for?
## HOW
Suggestions for how this may be solved. [Optional]
## TESTS
List of related tests
## DONE
Bullet point items for what should be completed

**Comment by sutaakar** [comment]
hi @ashahab,
Can you please link the change you are referring to?

**Comment by tedhtchang** [comment]
The user tried to install the codeflare-operator on KinD on macOS but failed to run `make install`.
we already updated the instruction in the [PR](https://github.com/project-codeflare/codeflare-operator/pull/298)
