### ISSUE TITLE
Set up unit tests

### ISSUE THREAD

**Issue by anishasthana** [project-codeflare/codeflare-operator#3]
We need to set up unit tests for the codeflare operator. This unit tests should be run as part of CI for every PR -- we can use openshift-ci for this.

**Comment by accorvin** [comment]
@anishasthana we are using github actions for this elsewhere in project-codeflare

**Comment by anishasthana** [comment]
Good point -- we can just use that instead assuming that's the path we settle on in #1

**Comment by anishasthana** [comment]
This was completed in #18
