### ISSUE TITLE
Test disconnected installation of stack..

### ISSUE THREAD

**Issue by abhijeet-dhumal** [project-codeflare/codeflare-operator#320]
The DW stack should be useable in a disconnected environment. This means a cluster whose internet access is limited to a single trusted registry for new images etc. In some cases it means completely disconnencted.

To test:

- the env must be set up
- the codeflare stack must be installed
- some sample notebooks should be run through to make sure all of the components are working

**Comment by dimakis** [comment]
@abhijeet-dhumal, new update we should also be testing on clusters with self-signed certs cc @sutaakar

**Comment by abhijeet-dhumal** [comment]
## Description

### Steps followed :
- [X]   Create disconnected cluster
- [X]   Create and config mirror registry for disconnected cluster
- [X]   Rhods installation with codeflare stack
- [X]   Ensure that all distributed workload components are working in an air-gapped environement

## How Has This Been Tested?



- I've made sure the tests are passing. 

- Testing Strategy
   - [X] Distributed workloads integration tests  
   - [X] Codeflare-SDK sample demo notebooks
   - [X] Documented all resolved/unresolved issues occurred with comprehensive instructions to troubleshoot

- New Approach tested
   - [X] Mirror index setup to access python package dependencies in disconnected environment 
   - [X] Local storage instance to access dataset files in disconnected environment
  
- I have documented these steps by implementing them thoroughly.
    [https://my-abhi-docs.notion.site/Test-disconnected-installation-of-stack-320-cdb404c5bbe34d30a9210d77dbf9d4d4?pvs=4](https://my-abhi-docs.notion.site/Test-disconnected-installation-of-stack-320-cdb404c5bbe34d30a9210d77dbf9d4d4?pvs=4)
