### ISSUE TITLE
Alter GH actions in the ODH/ RHDS CFO orgs to not use paid for GH runners

### ISSUE THREAD

**Issue by dimakis** [project-codeflare/codeflare-operator#377]
## What
We need to find a way to ignore [some GH actions](https://github.com/project-codeflare/codeflare-operator/blob/d851f6765a671928ebc80a962aa5220b666ce264/.github/workflows/e2e_tests.yaml#L30) during our automated syncing with ODH CFO (and its RHDS fork).

## Why
The e2e tests won't run and stay in a pending state

**Comment by sutaakar** [comment]
@dimakis I guess it can be removed and replaced by OpenShift CI testing, is it so?

**Comment by sutaakar** [comment]
GH workflow removal PR opened - https://github.com/opendatahub-io/codeflare-operator/pull/17

**Comment by sutaakar** [comment]
Reopening as RHDS CFO is not yet addressed
