### ISSUE TITLE
Update/ Add the action which creates the CF stack compatibility matrix

### ISSUE THREAD

**Issue by dimakis** [project-codeflare/codeflare-operator#380]
The KubeRay line in the compatibility matrix doesn't update. This needs to be fixed.

**Comment by dimakis** [comment]
@ChughShilpa the readme compatibility matrix doesn't get updated when we create a new tag (here)[https://github.com/opendatahub-io/kuberay/tags] this should be updated via an action preferably

**Comment by sutaakar** [comment]
@ChughShilpa can this issue be clodes?

**Comment by astefanutti** [comment]
it seems the latest run did not update the Kuberay version correctly: https://github.com/project-codeflare/codeflare-operator/pull/407/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R15.

**Comment by sutaakar** [comment]
Good catch, the parameter is missing in https://github.com/project-codeflare/codeflare-operator/blob/main/.github/workflows/project-codeflare-release.yml

**Comment by sutaakar** [comment]
Fix ready ^
