### ISSUE TITLE
Migrate MCAD Custom Resources over to this repository

### ISSUE THREAD

**Issue by anishasthana** [project-codeflare/codeflare-operator#50]
Once the operator bundle is created for the CodeFlare Operator, subscribing to this operator will create the CRDs by default. 

We should look into migrating https://github.com/project-codeflare/multi-cluster-app-dispatcher/tree/main/config/crd/bases over into this repository completely and changing mcad repository references to it to effectively be imports. An example of that would be https://github.com/kserve/modelmesh-serving/blob/main/controllers/servingruntime_controller.go#L38, which refers to https://github.com/kserve/kserve/tree/master/pkg/apis/serving/v1beta1

Alternatively, we need to come up with a better plan for keeping the 2 repositories in sync.

**Comment by astefanutti** [comment]
This has practically been addressed with #116.
