### ISSUE TITLE
Fix InstaScale CRD Display name

### ISSUE THREAD

**Issue by anishasthana** [project-codeflare/codeflare-operator#59]
The InstaScale CRD display name is wrong. We should fix the definition in the APIs folder as well as the following manifest updates for the operator as well as the bundle (and CSV).

_Originally posted by @Maxusmusti in https://github.com/project-codeflare/codeflare-operator/pull/41#discussion_r1129640136_

**Comment by tedhtchang** [comment]
This would be adding this 1 marker into the the the type definition and then re-make the bundle. The operator-sdk will re-gen the CSV. 
```
// +operator-sdk:csv:customresourcedefinitions:displayName="InstaScale"
type InstaScale struct {
...
```
