### ISSUE TITLE
Change InstaScale Configmap name

### ISSUE THREAD

**Issue by anishasthana** [project-codeflare/codeflare-operator#85]
Relevant InstaScale PR: https://github.com/project-codeflare/instascale/pull/52

InstaScale always expects a configmap with the name `instascale-config` to exist in a namespace. Our current configmap name does not align with that -- we should fix it.

**Comment by anishasthana** [comment]
As part of this we will also need to update the deployment template to pass in the configmap namespace.

**Comment by astefanutti** [comment]
This has become obsolete with #279.
