### ISSUE TITLE
Add replaces to the base CSV template and patch the value with the previous version

### ISSUE THREAD

**Issue by tedhtchang** [project-codeflare/codeflare-operator#98]
Since we have multiple versions we have an update path in the CSV file. We need to:
1. Add spec.replaces in the [base CSV file](https://github.com/project-codeflare/codeflare-operator/blob/main/config/manifests/bases/codeflare-operator.clusterserviceversion.yaml#L66)
2. Add/detect the previous version (in the [Makefile](https://github.com/project-codeflare/codeflare-operator/blob/main/Makefile))
Patch the value  of spec.replaces with the previous version. For example:
```
# best if we could detect this. If we cannot, we need to document it somewhere.
PREVIOUS_VERSION = 0.0.1 
# then we can add a patch in the `PHONY: bundle`
cd config/manifests && $(KUSTOMIZE) edit add patch --patch '[{"op":"add", "path":"/spec/replaces", "value": "codeflare-operator.v$(PREVIOUS_VERSION)" }]' --kind ClusterServiceVersion
```
See [here](
https://github.com/project-codeflare/codeflare-operator/pull/94#discussion_r1190298877) for more detail

**Comment by KPostOffice** [comment]
@tedhtchang 
Wouldn't having the name be independent of the version also fix this problem? Why is the operator version part of the CSV name field?

**Comment by KPostOffice** [comment]
I see elsewhere that it is in the name. I'm just confused as I don't see this "spec.replaces" defined in most other ClusterServiceVersions
